dbt_platform:
  outputs:
    ci:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_PORT', '5432') | int }}"
      user: "{{ env_var('DBT_USER', 'postgres') }}"
      password: "{{ env_var('DBT_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('DBT_DBNAME', 'dbt_platform') }}"
      schema: ci
      threads: 4
  target: ci
  