name: dbt CI

on:
    pull_request:
        branches:
            - main

jobs:
    dbt-ci:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:17
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: dbt_platform
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4.2.2

            - name: Set up Python
              uses: actions/setup-python@v5.6.0
              with: 
                python-version: '3.11'

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Load raw schema and seed data
              run: |
                PGPASSWORD=postgres psql -h localhost -U postgres -d dbt_platform -f init/01_raw_schema.sql
                PGPASSWORD=postgres psql -U postgres -h localhost -d dbt_platform -f init/02_raw_data.sql

            - name: Run dbt debug
              working-directory: dbt_platform
              env:
                DBT_HOST: localhost
                DBT_PORT: 5432
                DBT_USER: postgres
                DBT_PASSWORD: postgres
                DBT_DBNAME: dbt_platform
              run: dbt debug --profiles-dir .

            - name: Run dbt build 
              working-directory: dbt_platform
              env:
                DBT_HOST: localhost
                DBT_PORT: 5432
                DBT_USER: postgres
                DBT_PASSWORD: postgres
                DBT_DBNAME: dbt_platform
              run: dbt build --profiles-dir .
